url: https://memamun.github.io
baseurl: ""
title: Mamun Abdullah
description: >-
  Personal portfolio of Mamun Abdullah, software engineer and code enthusiast.
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
